use bon::Builder;
use egg::{Analysis, EGraph, Id, Language, Runner};

/// A macro for tracing messages if tracing is enabled in the program's configuration.
macro_rules! mtrace {
    ($s:ident, $kind:ident, $($t:tt)*) => {
        if $s.is_tracing_enabled($crate::DebugLevel::$kind) {
          eprintln!($($t)*)
        }
    };
}

/// Defines traits and structures for working with e-graph rules.
mod rule;
pub use rule::{DRule, Dependancy, Fresh, PrologRule, Rule};

/// Provides utilities for simplifying `and` expressions in e-graphs.
mod simplify_and;
pub use simplify_and::{WithAnd, WithTrue, and_simpl_rewrite};

/// Defines structures for weighting e-graph nodes.
mod weight;
pub use weight::MWeight;

/// Provides analysis capabilities for e-graphs.
mod analysis;
pub use analysis::{
    BeginResult, GData, GolggeAnalysis, HasMemo, MAnalysis, MemoCell, MemoKind, UserAnalysis,
    WeightedAnalysis,
};
pub use program::Program;
/// Defines structures for representing e-graph programs.
mod program;

/// Defines structures for representing proofs generated by the e-graph.
mod proof;
pub use proof::{ProofItem, SearchResult};

/// Proof export: serializable proof trees.
mod export;
pub use export::{LATEX_DOCUMENT_PREAMBLE, LangRender, ProofRenderer, ProofTree, latex_main};

mod config;
pub use config::{Config, DebugLevel, Flags};

#[cfg(feature = "sync")]
pub trait MaybeSyncSend: Sync + Send {}

#[cfg(feature = "sync")]
impl<T: Sync + Send> MaybeSyncSend for T {}

#[cfg(not(feature = "sync"))]
pub trait MaybeSyncSend {}

#[cfg(not(feature = "sync"))]
impl<T> MaybeSyncSend for T {}

/// canonicalize `id`, returns `true` if the value changed
#[inline]
fn canonicalize_id_mut<L: Language, N: Analysis<L>>(id: &mut Id, egraph: &EGraph<L, N>) -> bool {
    let nid = egraph.find(*id);
    let res = nid != *id;

    #[cfg(debug_assertions)]
    if res {
        println!("updated id from {id} to {nid}")
    }

    *id = nid;
    res
}
