use bon::Builder;
use egg::{Analysis, Language, Runner};

/// A macro for tracing messages if tracing is enabled in the program's configuration.
macro_rules! mtrace {
    ($s:ident, $kind:ident, $($t:tt)*) => {
        if $s.is_tracing_enabled($crate::DebugLevel::$kind) {
          eprintln!($($t)*)
        }
    };
}

mod tracing;
pub use tracing::DebugLevel;
/// Defines traits and structures for working with e-graph rules.
mod rule;
pub use rule::{DebugRule, Dependancy, Fresh, PrologRule, Rule};

/// Provides utilities for simplifying `and` expressions in e-graphs.
mod simplify_and;
pub use simplify_and::{WithAnd, WithTrue, and_simpl_rewrite};

/// Defines structures for weighting e-graph nodes.
mod weight;
pub use weight::MWeight;

/// Provides analysis capabilities for e-graphs.
mod analysis;
pub use analysis::{MAnalysis, WeightedAnalysis};
pub use program::Program;
/// Defines structures for representing e-graph programs.
mod program;

/// Provides structures for representing proofs generated by the e-graph.
mod proof;
pub use proof::ProofItem;

/// Configuration for the Golgge e-graph runner.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Builder)]
#[non_exhaustive]
pub struct Config {
    #[builder(default = Config::default().iter_limit)]
    pub iter_limit: usize,
    #[builder(default = Config::default().node_limit)]
    pub node_limit: usize,
    #[builder(default = Config::default().time_limit)]
    pub time_limit: std::time::Duration,
    #[builder(default = Config::default().trace)]
    pub trace: DebugLevel,
}

impl Config {
    /// Applies the configuration settings to an `egg::Runner`.
    pub fn apply<L: Language, N: Analysis<L>>(&self, runner: Runner<L, N>) -> Runner<L, N> {
        runner
            .with_iter_limit(self.iter_limit)
            .with_node_limit(self.node_limit)
            .with_time_limit(self.time_limit)
    }
}

impl Default for Config {
    /// Returns a default `Config` instance.
    fn default() -> Self {
        Self {
            iter_limit: 150,
            node_limit: 500,
            time_limit: std::time::Duration::from_secs(5),
            trace: DebugLevel::default()
        }
    }
}
