[package]
name = "cryptovampire_smt"
version = "0.1.0"
edition = "2024"
authors = ["Simon Jeanteur <simon.jeanteur@tuwien.ac.at>"]

[lints]
workspace = true

[dependencies]
utils = { path = "../utils"}
logic_formula = {path = "../logic_formula"}

log.workspace = true
env_logger.workspace = true
itertools.workspace = true
serde = { workspace = true, optional = true}

[features]
serde = ["utils/serde", "dep:serde"]
cryptovampire = ["vampire"]
vampire = []