[package]
name = "automator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.5.1"
pest_derive = "2.5.1"
static_init = "1.0.3"
paste = "1.0.9"
ord-utils = {git = "https://github.com/puyral/ord-utils"}
bitflags = "1.3.2"
crossbeam-utils = "0.8.14" # because I made poor choices
itertools = "0.10.5"
clap = { version = "4.0.32", features = ["derive"] }
