// pub mod base_function;
pub mod booleans;
pub mod evaluate;
// pub mod function_like;
pub mod if_then_else;
pub mod invalid_function;
// pub mod nonce;
pub mod predicate;
pub mod skolem;
pub mod step;
pub mod subterm;
pub mod term_algebra;
pub mod unused;
