[package]
name = "cryptovampire-lib"
version = "0.2.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utils ={ path = "../utils"}
# ord-utils = { git = "https://github.com/puyral/ord-utils" }
bitflags = "2.0.2"
anyhow = "1.0.68"

# qcell = "0.5.3"
# bumpalo = { version = "3.12.0", features = ["boxed", "collections"] }
# typed-arena = "2.0.2"

itertools = { workspace = true }
if_chain = { workspace = true }
hashbrown = { workspace = true }
log = { workspace = true }
static_init = { workspace = true }
paste = { workspace = true }
thiserror = { workspace = true }
macro-attr ={ workspace = true }