[package]
name = "cryptovampire-lib"
version = "0.2.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utils ={ path = "../utils"}
ord-utils = { git = "https://github.com/puyral/ord-utils" }
bitflags = "2.0.2"
# crossbeam-utils = "0.8.1 4" # because I made poor choices
# take_mut = "0.2.2"
thiserror = "1.0.38"
anyhow = "1.0.68"
# ouroboros = "0.17.0"
derivative = {version = "2.2.0"}
# aliasable = "0.1.3"
# qcell = "0.5.3"
# enum_dispatch = "0.3.11"
macro-attr = "0.2.0"
const_format = "0.2.31"
# qcell = "0.5.3"
# match_deref = "0.1.1"
# bumpalo = { version = "3.12.0", features = ["boxed", "collections"] }
# typed-arena = "2.0.2"
# either = "1.8.1"
env_logger = "0.10.0"
chrono = "0.4.31"

itertools = { workspace = true }
if_chain = { workspace = true }
hashbrown = { workspace = true }
log = { workspace = true }
static_init = { workspace = true }
paste = { workspace = true }